### PR TITLE
Fixed pause/unpause all alerts at once

### LINKED ISSUE #114: Pause/Unpause all alerts in one shot does not work
**Describe the bug**
Command `graf pause all alerts` and `graf unpause all alerts` does not work. Bot returns a permission denied error when trying in Slack. This is because the endpoint `admin/pause-all-alerts` is part of [Grafana Admin API](https://grafana.com/docs/http_api/admin/#pause-all-alerts) and it is clearly mentioned in Grafana documentation that _The Admin HTTP API does not currently work with an API Token._

**To Reproduce**
1. Data source '...'
2. Command entered `myhubot graf unpause all alerts`
3. In slack it says permission denied. In Grafana logs its logged that grafana responded with 403.

**Expected behavior**
It should pause all alerts in one go.

**Software:**
 - Grafana: v6.2.4
 - Hubot: latest
 - Adapter: Slack, or Any
 - Node: <version>
 - NPM: <version>

### PR DESCRIPTION
**Pull request by liptanbiswas**
Fixes #114. As we can not use admin credentials, we can loop through all alerts and pause/unpause them one by one. I don't see any other way as it would be useless to use admin credentials just for this. Also, in order to use admin API, username and password needs to be supplied as basic auth.

### CODE REVIEW

File: src/grafana.coffee [hunk 1]
```diff
@@ -313,10 +313,17 @@ module.exports = (robot) ->
...
-      robot.logger.debug result
-      if result.message
-        msg.send result.message
+    callGrafana endpoint, 'alerts', (alerts) ->
+      robot.logger.debug alerts
+      errored = 0
+      unless alerts.length > 0
+        return
+      for alert in alerts
+        postGrafana endpoint, "alerts/#{alert.id}/pause", {'paused': paused}, (result) ->
```
Comment (stephenyeargin) [inline src/grafana.coffee]: So, if I'm reading this right, you can't actually _unpause_ all alerts in either this version or the previous one.

Comment (liptanbiswas) [reply src/grafana.coffee]: @stephenyeargin Reagrding Unpause: 
See https://github.com/stephenyeargin/hubot-grafana/blob/master/src/grafana.coffee#L311
In case of _unpause_, **paused** becomes false and see line 322 above, it will send `{'paused': 'false'}` as request body which will unpause the alert. 
Regarding **all alerts**: Yeah, this will pause/unpause all alert in the organization of that API key, so if there are multiple organization, it will only deal with the alerts which are tied to that organization.

Comment (stephenyeargin) [reply src/grafana.coffee]: Ah, was thrown off by the original variable name. Likely should have been called `action` or something so it was a bit clearer. Either way, makes sense. :+1:
